### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by rgarimella0124** [akiarostami/sveltekit-tailwind-blog-starter#8]
First of all, Excellent Work. I have been wanting to start a blog and your template has all the checkboxes.
For my blog, I don't need authors at all. So when I tried removing the author's folder, the entire posts disappeared showing error 404, how do i fix them?

Cannot read properties of undefined (reading 'name')
TypeError: Cannot read properties of undefined (reading 'name')
    at Blog.svelte:59:31
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1876:22)
    at eval (/src/routes/blog/[slug]/+page.svelte:22:83)
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1876:22)
    at Object.default (root.svelte:41:38)
    at Object.default (/src/routes/+layout.svelte:27:43)
    at eval (/src/lib/components/layout/Transition.svelte:13:46)
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1876:22)
    at eval (/src/routes/+layout.svelte:25:118)
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1876:22)

this the error i get for deleting all markdowns of aruthors

**Comment by akiarostami** [comment]
Thanks, @rgarimella0124. Where is the "author folder"? I can't seem to find any folder with that name! But 404 sounds like a routing issue, and you have to check your Sveltekit routing.

Overall, many parts of this template are outdated, and I need to clean up many parts.

**Comment by rgarimella0124** [comment]
@akiarostami I was talking about the author folder inside the content folder, but that is solved. Apologies for not coming back. Just like the previous issue. But to TBH, your post on the deployment to netlify has made my life so easy that all I have to do now is put my markdown file in the content folder and push it to GitHub, it becomes live within 5 mins.  Thanks a lot for this. 

I have one quick question. Assuming the blog goes well. and you create more than 200 posts. so is it feasible to use GitHub for dropping our md files, this will consistently increase our GitHub project size, assuming the maximum size of one md file is 20 kb. Is there a solution to this? Where we put our content in storage like Amazon S3 or Azure Blob Storage. Can the website pull them directly from there?

Let me know i am not thinking straight, i highly value any advice you can give me.

**Comment by akiarostami** [comment]
Oh! Now I know where you're talking about! As you clearly I don't remember the details of the code :), but I'm searching for that folder in code. Simple search for Author in the code and comment it out. It should work correctly. I did that for my own blog as well.

Github should have no problem handling 200 (or even a thousand) posts. There is even a better (and faster) solution, which is turning the site into a static site. But for that, you'd need to make several changes in the code, and would lose some features like tag search. That's on my to-do list for the next version of this, whenever I get to do it!
