### ISSUE TITLE
Build error in netlify 

### ISSUE THREAD

**Issue by rgarimella0124** [akiarostami/sveltekit-tailwind-blog-starter#9]
5:56:49 PM: Netlify Build                                                 
5:56:49 PM: ────────────────────────────────────────────────────────────────
5:56:49 PM: ​
5:56:49 PM: ❯ Version
5:56:49 PM:   @netlify/build 29.36.3
5:56:49 PM: ​
5:56:49 PM: ❯ Flags
5:56:49 PM:   baseRelDir: true
5:56:49 PM:   buildId: 65fad5e41e29290008e16720
5:56:49 PM:   deployId: 65fad5e41e29290008e16722
5:56:49 PM: ​
5:56:49 PM: ❯ Current directory
5:56:49 PM:   /opt/build/repo
5:56:49 PM: ​
5:56:49 PM: ❯ Config file
5:56:49 PM:   /opt/build/repo/netlify.toml
5:56:49 PM: ​
5:56:49 PM: ❯ Context
5:56:49 PM:   production
5:56:49 PM: ​
5:56:49 PM: build.command from netlify.toml                               
5:56:49 PM: ────────────────────────────────────────────────────────────────
5:56:49 PM: ​
5:56:49 PM: $ npm run build
5:56:49 PM: > brainstew@1.0.0 build
5:56:49 PM: > vite build
5:56:50 PM: 
5:56:50 PM: (!) Experimental legacy.buildSsrCjsExternalHeuristics and ssr.format: "cjs" are going to be removed in Vite 5.
5:56:50 PM:     Find more information and give feedback at https://github.com/vitejs/vite/discussions/13816.
5:56:50 PM: 
5:56:50 PM: vite v4.5.1 building SSR bundle for production...
5:56:50 PM: transforming...
5:56:50 PM: src/routes/+layout.svelte
5:56:50 PM: `export const prerender` will be ignored — move it to +layout(.server).js/ts instead. See https://kit.svelte.dev/docs/page-options for more information.
5:56:52 PM: ✓ 115 modules transformed.
5:56:52 PM: rendering chunks...
5:56:53 PM: 
5:56:53 PM: (!) Experimental legacy.buildSsrCjsExternalHeuristics and ssr.format: "cjs" are going to be removed in Vite 5.
5:56:53 PM:     Find more information and give feedback at https://github.com/vitejs/vite/discussions/13816.
5:56:53 PM: 
5:56:53 PM: vite v4.5.1 building for production...
5:56:53 PM: transforming...
5:56:54 PM: ✓ 83 modules transformed.
5:56:54 PM: rendering chunks...
5:56:54 PM: computing gzip size...
5:56:54 PM: .svelte-kit/output/client/_app/version.json                              0.03 kB │ gzip: 0.05 kB
5:56:54 PM: .svelte-kit/output/client/.vite/manifest.json                            4.06 kB │ gzip: 0.61 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/assets/0.d908d468.css          44.01 kB │ gzip: 7.38 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/chunks/stores.2f35f87a.js       0.24 kB │ gzip: 0.17 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/nodes/3.98bb3647.js             0.83 kB │ gzip: 0.48 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/nodes/5.484d7199.js             0.92 kB │ gzip: 0.50 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/chunks/theme.e6db67f9.js        1.37 kB │ gzip: 0.73 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/nodes/2.dc8c6a74.js             1.78 kB │ gzip: 0.91 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/nodes/1.d22bbaaa.js             1.88 kB │ gzip: 0.80 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/chunks/singletons.0bac7f08.js   2.91 kB │ gzip: 1.50 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/entry/app.b6d40f0a.js           6.65 kB │ gzip: 2.43 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/chunks/Tag.e7d9ee10.js          9.59 kB │ gzip: 3.96 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/chunks/index.58156986.js       11.14 kB │ gzip: 4.73 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/chunks/Blogs.f5d38643.js       12.38 kB │ gzip: 4.74 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/nodes/0.5403a17e.js            14.68 kB │ gzip: 5.29 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/entry/start.d07c6e53.js        25.31 kB │ gzip: 9.99 kB
5:56:54 PM: .svelte-kit/output/client/_app/immutable/nodes/4.25ec447f.js            26.36 kB │ gzip: 7.91 kB
5:56:54 PM: ✓ built in 972ms
5:56:54 PM: node:internal/event_target:1062
5:56:54 PM:   process.nextTick(() => { throw err; });
5:56:54 PM:                            ^
5:56:54 PM: Error [ERR_MODULE_NOT_FOUND]: Cannot find package "devalue" imported from /opt/build/repo/.svelte-kit/output/server/index.js
5:56:54 PM: Did you mean to import devalue@4.3.2/node_modules/devalue/index.js?
5:56:54 PM:     at new NodeError (node:internal/errors:405:5)
5:56:54 PM:     at packageResolve (node:internal/modules/esm/resolve:916:9)
5:56:54 PM:     at moduleResolve (node:internal/modules/esm/resolve:973:20)
5:56:54 PM:     at defaultResolve (node:internal/modules/esm/resolve:1193:11)
5:56:54 PM:     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:403:12)
5:56:54 PM:     at ModuleLoader.resolve (node:internal/modules/esm/loader:372:25)
5:56:54 PM:     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:249:38)
5:56:54 PM:     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
5:56:54 PM:     at link (node:internal/modules/esm/module_job:75:36)
5:56:54 PM: Emitted "error" event on Worker instance at:
5:56:54 PM:     at [kOnErrorMessage] (node:internal/worker:314:10)
5:56:54 PM:     at [kOnMessage] (node:internal/worker:325:37)
5:56:54 PM:     at MessagePort.<anonymous> (node:internal/worker:225:57)
5:56:54 PM:     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:786:20)
5:56:54 PM:     at exports.emitMessage (node:internal/per_context/messageport:23:28) {
5:56:54 PM:   code: "ERR_MODULE_NOT_FOUND"
5:56:54 PM: }
5:56:54 PM: Node.js v18.19.1
5:56:54 PM: ​
5:56:54 PM: "build.command" failed                                        
5:56:54 PM: ────────────────────────────────────────────────────────────────
5:56:54 PM: ​
5:56:54 PM:   Error message
5:56:54 PM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
5:56:54 PM: ​
5:56:54 PM:   Error location
5:56:54 PM:   In build.command from netlify.toml:
5:56:54 PM:   npm run build
5:56:54 PM: ​
5:56:54 PM:   Resolved config
5:56:54 PM:   build:
5:56:54 PM:     command: npm run build
5:56:54 PM:     commandOrigin: config
5:56:54 PM:     environment:
5:56:54 PM:       - DEPRECATED
5:56:54 PM:     publish: /opt/build/repo/build
5:56:54 PM:     publishOrigin: config
5:56:54 PM:   functionsDirectory: /opt/build/repo/functions
5:56:55 PM: Failed during stage "building site": Build script returned non-zero exit code: 2
5:56:55 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
5:56:55 PM: Failing build: Failed to build site
5:56:55 PM: Finished processing build request in 29.757s

**Comment by rgarimella0124** [comment]
Please find the above netlify logs and suggest a fix i am not able to push new markdown files into the blog

**Comment by akiarostami** [comment]
Hello,

All libraries have changed since I released this, Svelte, Sveltekit, Netlify, and several others. From the message it seems that one of the libraries has DEPRECATED, but I'm not sure which one. This was just a sample code to be used as a reference, not a library, so I haven't updated it. Sorry about that.

**Comment by rgarimella0124** [comment]
@akiarostami I have fixed the issue, infact i have upgraded all the packages to their latest verisions and it is working well in local as well as in production, I have created a gist which specifies changes in two files and upon doing this it will run smoother than before, 
https://gist.github.com/rgarimella0124/0fef7c9d105e44d3822a37ff961111ed

I am not able to create a PR due to some restrctions on the repo. Kindly update the two files and we can close this issuw

**Comment by akiarostami** [comment]
@rgarimella0124 Done, and thank you!
